package com.hesoyam.mercury.form;

import com.hesoyam.mercury.model.ProductPrice;
import com.hesoyam.mercury.model.invoice.BuyerInfo;
import com.hesoyam.mercury.model.invoice.InvoiceInfo;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.*;
import java.util.ArrayList;
import java.util.List;

import static com.hesoyam.mercury.reader.AvailableProductsReader.getAvailableProducts;
import static com.hesoyam.mercury.reader.CounterpartyInfoReader.getCounterpartyInfo;
import static com.hesoyam.mercury.reader.FirmInfoReader.getFirmInfo;
import static com.hesoyam.mercury.reader.ProductsPriceInfoReader.getProductsPriceInfo;
import static com.hesoyam.mercury.util.ServiceUtil.*;
import static com.hesoyam.mercury.writer.MonthlyInvoiceWriter.extractInvoicesDoc;
import static com.hesoyam.mercury.writer.TradeFilesWriter.createAllTradesFiles;
import static com.hesoyam.mercury.writer.TradeFilesWriter.createDailyTrade;

/**
 * @author grivov
 */
public class MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public MainJPanel() {
        initComponents();

        if (!isFileEmpty(AVAILABLE_PRODUCTS_FILE_PATH)) {
            productName.setModel(new DefaultComboBoxModel(extractAvailableProducts()));
        }
        if (!isFileEmpty(COUNTERPARTY_INFO_FILE_PATH)) {
            recipient.setModel(new DefaultComboBoxModel(extractAvailableRecipients()));
        }

        checkIfFileIsEmptyAndChangeLabel(FIRM_INFO_FILE_PATH, jLabel9);
        checkIfFileIsEmptyAndChangeLabel(COUNTERPARTY_INFO_FILE_PATH, jLabel10);
        checkIfFileIsEmptyAndChangeLabel(AVAILABLE_PRODUCTS_FILE_PATH, jLabel11);
        checkIfFileIsEmptyAndChangeLabel(PRODUCTS_PRICE_FILE_PATH, jLabel12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        productName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        recipient = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        productQuantity = new javax.swing.JTextField();
        manufactureTime = new javax.swing.JTextField();
        deliveryTime = new javax.swing.JTextField();
        createFileButton = new javax.swing.JButton();
        getAllFilesForTodayButton = new javax.swing.JButton();
        getMonthlyInvoiceButton = new javax.swing.JButton();
        expiryDate = new org.jdesktop.swingx.JXDatePicker();
        manufactureDate = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/hesoyam/mercury/form/Bundle"); // NOI18N
        jLabel5.setText(bundle.getString("MainJPanel.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setText(bundle.getString("MainJPanel.jLabel1.text")); // NOI18N

        productName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        jLabel2.setText(bundle.getString("MainJPanel.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("MainJPanel.jLabel3.text")); // NOI18N

        jLabel4.setText(bundle.getString("MainJPanel.jLabel4.text")); // NOI18N

        jLabel6.setText(bundle.getString("MainJPanel.jLabel6.text")); // NOI18N

        jLabel7.setText(bundle.getString("MainJPanel.jLabel7.text")); // NOI18N

        recipient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        jLabel8.setText(bundle.getString("MainJPanel.jLabel8.text")); // NOI18N

        productQuantity.setText(bundle.getString("MainJPanel.productQuantity.text")); // NOI18N

        manufactureTime.setText(bundle.getString("MainJPanel.manufactureTime.text")); // NOI18N

        deliveryTime.setText(bundle.getString("MainJPanel.deliveryTime.text")); // NOI18N

        createFileButton.setText(bundle.getString("MainJPanel.createFileButton.text")); // NOI18N
        createFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFileButtonActionPerformed(evt);
            }
        });

        getAllFilesForTodayButton.setText(bundle.getString("MainJPanel.getAllFilesForTodayButton.text")); // NOI18N
        getAllFilesForTodayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllFilesForTodayButtonActionPerformed(evt);
            }
        });

        getMonthlyInvoiceButton.setText(bundle.getString("MainJPanel.getMonthlyInvoiceButton.text")); // NOI18N
        getMonthlyInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getMonthlyInvoiceButtonActionPerformed(evt);
            }
        });

        jButton1.setText(bundle.getString("MainJPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(bundle.getString("MainJPanel.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText(bundle.getString("MainJPanel.jLabel9.text")); // NOI18N

        jLabel10.setText(bundle.getString("MainJPanel.jLabel10.text")); // NOI18N

        jLabel11.setText(bundle.getString("MainJPanel.jLabel11.text")); // NOI18N

        jButton3.setText(bundle.getString("MainJPanel.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText(bundle.getString("MainJPanel.jLabel12.text")); // NOI18N

        jButton4.setText(bundle.getString("MainJPanel.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel8)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel6)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                                .addComponent(recipient, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                                                                                                .addComponent(productName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                                        .addComponent(jLabel3)))
                                                                                        .addComponent(manufactureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(22, 22, 22)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(manufactureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(jLabel2)
                                                                                                .addComponent(productQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(jLabel4)))
                                                                        .addComponent(deliveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(createFileButton)
                                                                        .addComponent(getAllFilesForTodayButton))
                                                                .addComponent(jLabel9)
                                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                                                .addComponent(jLabel11)
                                                                .addComponent(jLabel12)
                                                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(getMonthlyInvoiceButton))
                                                .addContainerGap(48, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(productQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(manufactureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(manufactureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recipient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deliveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(createFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getAllFilesForTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getMonthlyInvoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        createDailyTrade(recipient, productName, productQuantity, manufactureDate, manufactureTime, deliveryTime, expiryDate);
    }

    private void getAllFilesForTodayButtonActionPerformed(java.awt.event.ActionEvent evt) {
        createAllTradesFiles();
    }

    private void getMonthlyInvoiceButtonActionPerformed(ActionEvent evt) {
        extractInvoicesDoc();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        getFirmInfo(jLabel9);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        getCounterpartyInfo(jLabel10, recipient);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        getAvailableProducts(jLabel11, productName);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        getProductsPriceInfo(jLabel12);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createFileButton;
    private javax.swing.JTextField deliveryTime;
    private org.jdesktop.swingx.JXDatePicker expiryDate;
    private javax.swing.JButton getAllFilesForTodayButton;
    private javax.swing.JButton getMonthlyInvoiceButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXDatePicker manufactureDate;
    private javax.swing.JTextField manufactureTime;
    private javax.swing.JComboBox<String> productName;
    private javax.swing.JTextField productQuantity;
    private javax.swing.JComboBox<String> recipient;
    // End of variables declaration//GEN-END:variables
}
